### ISSUE TITLE
localStorage key name "Conviva.sdkConfig" in enums

### ISSUE THREAD

**Issue by rtkac** [Conviva/conviva-js-coresdk#3]
Hello,
is there a way how to get a name of the key "Conviva.sdkConfig" that is in the localStorage? 
It would be great if it's in the enums in the conviva-core-sdk.d.ts.

The problem is when I need to clear the localStorage except for "Conviva.sdkConfig". I can access to it directly
`localStorage.getItem('Conviva.sdkConfig')`
but what if you change the key name?
it would be cleaner by
`localStorage.getItem(ConvivaKeys.SDK_CONFIG)`

Thanks a lot!

**Comment by kedarmarsada** [comment]
Thank you for the suggestion. We will consider it in our future releases.
