### ISSUE TITLE
Version 4.7.5 Being Reported Instead of 4.7.6

### ISSUE THREAD

**Issue by mattg-ensemble** [Conviva/conviva-js-coresdk#5]
Hello,

I'm noticing in touchstone the "Conviva Core Ve" is being reported as version 4.7.5 instead of 4.7.6. I have confirmed I am using the latest version on my end.

It looks like version 4.7.5 is still present in multiple places in the conviva-core-sdk.js file (this might be the source of the issue?)

Thanks!

**Comment by kedarmarsada** [comment]
Fixed in latest build
